### ISSUE TITLE
Getting speaker embeddings 

### ISSUE THREAD

**Issue by AH289** [microsoft/UniSpeech#13]
UniSpeech-SAT directory in this repo contains an example. The example takes a .wav file as an input and produces a tensor 'f' as an output. Can I get the speaker embeddings from 'f'?

**Comment by MarkWuNLP** [comment]
> UniSpeech-SAT directory in this repo contains an example. The example takes a .wav file as an input and produces a tensor 'f' as an output. Can I get the speaker embeddings from 'f'?

Hi,
    If you would like to get speaker embeddings, you can refer to what we have done for speaker verification https://github.com/microsoft/UniSpeech/tree/main/UniSpeech-SAT/speaker_verification .  @czy97  Add Zhengyang into the thread.

**Comment by czy97** [comment]
> UniSpeech-SAT directory in this repo contains an example. The example takes a .wav file as an input and produces a tensor 'f' as an output. Can I get the speaker embeddings from 'f'?

Specifically, you can get the speaker embedding from this line: https://github.com/microsoft/UniSpeech/blob/866ad28bdb3615263d4f77d36a64fbe564a412b0/UniSpeech-SAT/speaker_verification/verification.py#L50

**Comment by AH289** [comment]
Thank you so much.
