### ISSUE TITLE
UniSpeech-SAT/speaker_verification: torchaudio version

### ISSUE THREAD

**Issue by msh9184** [microsoft/UniSpeech#17]
Hello,
In UniSpeech-SAT/speaker_verification/verification.py file,
resample function of torchaudio.functional seems to be only supported from torchaudio version 0.9.0 or higher.
For the versions below 0.9.0, there seems to be Resample function of  torchaudio.transforms.
Thanks.

**Comment by czy97** [comment]
> Hello, In UniSpeech-SAT/speaker_verification/verification.py file, resample function of torchaudio.functional seems to be only supported from torchaudio version 0.9.0 or higher. For the versions below 0.9.0, there seems to be Resample function of torchaudio.transforms. Thanks.

Thanks for the comment, I have updated the code to be compatible with old torchaudio versions.
