### ISSUE TITLE
Missing recipe/code for speaker verification

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [microsoft/UniSpeech#18]
Few days back, I was able to access UniSpeech-SAT/speaker_verification/ for Ecapa-tdnn recipe. But now its been removed from github repo. Do you have any plans to include this repo Or its not going to get added in future?

Thanks
Ajinkya Kulkarni

**Comment by MarkWuNLP** [comment]
It is moved to here https://github.com/microsoft/UniSpeech/tree/main/downstreams/speaker_verification
