### ISSUE TITLE
Unispeech-SAT fairseq code

### ISSUE THREAD

**Issue by RuslanSel** [microsoft/UniSpeech#20]
Hi!

From UniSpeech/downstreams/speaker_diarization/README.md:
For UniSpeech-SAT large, we should install the Unispeech-SAT fairseq code.

Where can I find the Unispeech-SAT fairseq code?

Thanks in advance.

**Comment by cywang97** [comment]
@RuslanSel 
Hi, we have re-organized the repo. Currently, Unispeech(-SAT) and WavLM are sharing the same fairseq codebase. You can install fairseq in src/ directory by running: pip install --editable ./

**Comment by RuslanSel** [comment]
Thanks.
pip install --editable ./ gives gcc: error: fairseq/clib/libbleu/libbleu.cpp: No such file or directory.
There is fairseq/clib directory in the https://github.com/pytorch/fairseq/tree/main/fairseq, but not in the https://github.com/microsoft/UniSpeech/tree/main/src/fairseq.

**Comment by MarkWuNLP** [comment]
@RuslanSel  We wrongly deleted these files in code refinement. I just added these files back.

**Comment by RuslanSel** [comment]
Thanks.
