### ISSUE TITLE
diarization - KeyError: 'embed.weight'

### ISSUE THREAD

**Issue by RuslanSel** [microsoft/UniSpeech#21]
I got the error running python diarization.py --config_path config/infer_est_nspk1.yaml --wav_path 0.wav --model_init WavLM-Large.pt
Traceback (most recent call last):
  File "diarization.py", line 321, in <module>
    main(args)
  File "diarization.py", line 272, in main
    model_all_n_speakers = model_parameter_dict["embed.weight"].shape[0]
KeyError: 'embed.weight'

Thanks in advance.

**Comment by MarkWuNLP** [comment]
Hi, @RuslanSel ,  @czy97   will answer your question

**Comment by czy97** [comment]
> I got the error running python diarization.py --config_path config/infer_est_nspk1.yaml --wav_path 0.wav --model_init WavLM-Large.pt Traceback (most recent call last): File "diarization.py", line 321, in main(args) File "diarization.py", line 272, in main model_all_n_speakers = model_parameter_dict["embed.weight"].shape[0] KeyError: 'embed.weight'
> 
> Thanks in advance.

Sorry for the late reply. Maybe you downloaded the model from the wrong url. We have saved the pre-trained model and the down-stream diarization model in the same checkpoint file.  You should download the model from here: https://drive.google.com/file/d/16OwIyOk2uYm0aWtSPaS0S12xE8RxF7k_/view?usp=sharing, which is referenced in the result Table of https://github.com/microsoft/UniSpeech/tree/main/downstreams/speaker_diarization.

**Comment by RuslanSel** [comment]
Yes. I downloaded the model from the main README.md.
Thanks.

**Comment by luhuijun666** [comment]
> > I got the error running python diarization.py --config_path config/infer_est_nspk1.yaml --wav_path 0.wav --model_init WavLM-Large.pt Traceback (most recent call last): File "diarization.py", line 321, in main(args) File "diarization.py", line 272, in main model_all_n_speakers = model_parameter_dict["embed.weight"].shape[0] KeyError: 'embed.weight'
> > Thanks in advance.
> 
> Sorry for the late reply. Maybe you downloaded the model from the wrong url. We have saved the pre-trained model and the down-stream diarization model in the same checkpoint file. You should download the model from here: https://drive.google.com/file/d/16OwIyOk2uYm0aWtSPaS0S12xE8RxF7k_/view?usp=sharing, which is referenced in the result Table of https://github.com/microsoft/UniSpeech/tree/main/downstreams/speaker_diarization.

The url is missing~

**Comment by v-nhandt21** [comment]
@RuslanSel  @czy97 , can you share the model link again because the link cannot access, thanks too much
