### ISSUE TITLE
Where is the trainning/test/infer recipe?

### ISSUE THREAD

**Issue by leijue222** [microsoft/UniSpeech#27]
Is the recipes in s3prl?

I see [unispeech_sat ](https://github.com/s3prl/s3prl/tree/master/s3prl/upstream/unispeech_sat) and [wavlm](https://github.com/s3prl/s3prl/tree/master/s3prl/upstream/wavlm) in s3prl, and do not find any train/test/infer code in this repository.

[WavLM SV demo in s3prl](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/docs/superb.md#asv-automatic-speaker-verification):

- Traing demo in s3prl repository:

`python3 run_downstream.py -n wavlm -m train -u fbank -d sv_voxceleb1`

- Test demo in s3prl repository:

`python3 run_downstream.py -m evaluate -e result/downstream/wavlm/wavlm_large_finetune.pth`

- Infer demo in UniSpeech repository:

https://github.com/microsoft/UniSpeech/tree/main/downstreams/speaker_verification#example

**Comment by Sanyuan-Chen** [comment]
Hi @leijue222 ,

The recipe for SUPERB evaluation can be found in [s3prl repo](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/docs/superb.md#asv-automatic-speaker-verification), and the recipe for ASR fine-tuning can be found in [fairseq repo](https://github.com/facebookresearch/fairseq/tree/main/examples/hubert). And the recipes for other downstream tasks are currently not available.
