### ISSUE TITLE
WavLM Inference Error

### ISSUE THREAD

**Issue by bryant0918** [microsoft/UniSpeech#29]
I loaded the WaveLM Large model from the link provided

When trying to follow the code for loading the pretrained model for inference I get the following error:
cfg = WavLMConfig(checkpoint['cfg'])
KeyError: 'cfg'

It looks like this model does not have any 'cfg' key or 'model' key for that matter.

**Comment by Sanyuan-Chen** [comment]
Hi @bryant0918 ,

I just downloaded the WaveLM Large model with the [Azure Storage Link](https://msranlcmtteamdrive.blob.core.windows.net/share/wavlm/WavLM-Large.pt?sv=2020-08-04&st=2021-11-22T10%3A03%3A53Z&se=2022-11-23T10%3A03%3A00Z&sr=b&sp=r&sig=3kB8dwTCyIS8YQ7gW5oXmDrXV%2FAaLmoxBS37oPpFsz4%3D) and the [Google Drive Link](https://drive.google.com/file/d/1p8nbj16b7YA16sqPZ4E0JUL-oIDUBGwU/view?usp=sharing), and both models seem fine and contain the 'cfg' and 'model' keys. Could you please try again with these two links?

**Comment by bryant0918** [comment]
Thank you, I originally downloaded the microsoft/wavlm-large model from huggingface and it seems to be a little different.
