### ISSUE TITLE
Hello, I want to do the voiceprint verification task, the model chooses unispeech_sat, but it keeps getting an error, please help

### ISSUE THREAD

**Issue by zuihaodeyujian** [microsoft/UniSpeech#31]
1.Command 
![image](https://user-images.githubusercontent.com/109508871/179468177-f681a102-e997-42a4-99bd-c73e2a04c3d2.png)
2.error
![image](https://user-images.githubusercontent.com/109508871/179468410-2ace1ad3-bb3c-4898-8875-7843e766b82c.png)

**Comment by OrangeMiaoC** [comment]
I also encountered a similar problem. May you installed the fairseq and you can use "conda list" to check it. If you have installed fairseq, you can uninstall it.  And copy 'src/fairseq' to your project.  And there are some problems in the 'src/examples/speaker_verification/config/unispeech_sat.th', you can download this https://github.com/microsoft/UniSpeech/blob/2816e682dcec4661384cfe0c01f4121641c9954c/UniSpeech-SAT/speaker_verification/config/unispeech_sat.th

**Comment by zuihaodeyujian** [comment]
> I also encountered a similar problem. May you installed the fairseq and you can use "conda list" to check it. If you have installed fairseq, you can uninstall it. And copy 'src/fairseq' to your project. And there are some problems in the 'src/examples/speaker_verification/config/unispeech_sat.th', you can download this https://github.com/microsoft/UniSpeech/blob/2816e682dcec4661384cfe0c01f4121641c9954c/UniSpeech-SAT/speaker_verification/config/unispeech_sat.th

Thank you, this problem has been solved, but I have encountered a new problem, please help
![image](https://user-images.githubusercontent.com/109508871/188592311-3b29dc60-aa28-422c-88b7-66eaf7d8f72d.png)

**Comment by liyunlongaaa** [comment]
> > I also encountered a similar problem. May you installed the fairseq and you can use "conda list" to check it. If you have installed fairseq, you can uninstall it. And copy 'src/fairseq' to your project. And there are some problems in the 'src/examples/speaker_verification/config/unispeech_sat.th', you can download this https://github.com/microsoft/UniSpeech/blob/2816e682dcec4661384cfe0c01f4121641c9954c/UniSpeech-SAT/speaker_verification/config/unispeech_sat.th
> 
> Thank you, this problem has been solved, but I have encountered a new problem, please help ![image](https://user-images.githubusercontent.com/109508871/188592311-3b29dc60-aa28-422c-88b7-66eaf7d8f72d.png)

hi, can you solve this problem? I also encountered it. Thank you

**Comment by zuihaodeyujian** [comment]
> > > I also encountered a similar problem. May you installed the fairseq and you can use "conda list" to check it. If you have installed fairseq, you can uninstall it. And copy 'src/fairseq' to your project. And there are some problems in the 'src/examples/speaker_verification/config/unispeech_sat.th', you can download this https://github.com/microsoft/UniSpeech/blob/2816e682dcec4661384cfe0c01f4121641c9954c/UniSpeech-SAT/speaker_verification/config/unispeech_sat.th
> > 
> > 
> > Thank you, this problem has been solved, but I have encountered a new problem, please help ![image](https://user-images.githubusercontent.com/109508871/188592311-3b29dc60-aa28-422c-88b7-66eaf7d8f72d.png)
> 
> hi, can you solve this problem? I also encountered it. Thank you

hi，I haven't solved it yet, Which path is your ”unispeech_sat.th “using?

**Comment by liyunlongaaa** [comment]
> > > > I also encountered a similar problem. May you installed the fairseq and you can use "conda list" to check it. If you have installed fairseq, you can uninstall it. And copy 'src/fairseq' to your project. And there are some problems in the 'src/examples/speaker_verification/config/unispeech_sat.th', you can download this https://github.com/microsoft/UniSpeech/blob/2816e682dcec4661384cfe0c01f4121641c9954c/UniSpeech-SAT/speaker_verification/config/unispeech_sat.th
> > > 
> > > 
> > > Thank you, this problem has been solved, but I have encountered a new problem, please help ![image](https://user-images.githubusercontent.com/109508871/188592311-3b29dc60-aa28-422c-88b7-66eaf7d8f72d.png)
> > 
> > 
> > hi, can you solve this problem? I also encountered it. Thank you
> 
> hi，I haven't solved it yet, Which path is your ”unispeech_sat.th “using?



> > > > I also encountered a similar problem. May you installed the fairseq and you can use "conda list" to check it. If you have installed fairseq, you can uninstall it. And copy 'src/fairseq' to your project. And there are some problems in the 'src/examples/speaker_verification/config/unispeech_sat.th', you can download this https://github.com/microsoft/UniSpeech/blob/2816e682dcec4661384cfe0c01f4121641c9954c/UniSpeech-SAT/speaker_verification/config/unispeech_sat.th
> > > 
> > > 
> > > Thank you, this problem has been solved, but I have encountered a new problem, please help ![image](https://user-images.githubusercontent.com/109508871/188592311-3b29dc60-aa28-422c-88b7-66eaf7d8f72d.png)
> > 
> > 
> > hi, can you solve this problem? I also encountered it. Thank you
> 
> hi，I haven't solved it yet, Which path is your ”unispeech_sat.th “using?

I already give up, fucking code
