### ISSUE TITLE
Access Required for UniSpeech-SAT models

### ISSUE THREAD

**Issue by patrickvonplaten** [microsoft/UniSpeech#4]
Would it be possible to give everyone access to the UniSpeech-SAT models. Currently one cannot download the checkpoints for UniSpeech-SAT as the link is a google drive and requires access, *e.g.*: https://drive.google.com/file/d/1l5etRW6W2aP_8I2Fs_8ailGZqEzdrAPz/view?usp=sharing

**Comment by MarkWuNLP** [comment]
> Would it be possible to give everyone access to the UniSpeech-SAT models. Currently one cannot download the checkpoints for UniSpeech-SAT as the link is a google drive and requires access, _e.g._: https://drive.google.com/file/d/1l5etRW6W2aP_8I2Fs_8ailGZqEzdrAPz/view?usp=sharing

The link is turned on. Issue closed. Our paper: https://arxiv.org/pdf/2110.05752.pdf
